version: '2'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    image: peterkr/project_app_mysql
    ports:
      - "3306:3306"
    restart: always

  phonebook-app:
    container_name: phonebook-app
    image: peterkr/project_app
    depends_on:
      - phonebook-mysql
    ports:
      - "8181:8181"
    restart: always
